apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/C/tmp