// <auto-generated />
using Howest.MCT.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace examen.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20231222080509_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Howest.models.Broadcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int>("SerieId")
                        .HasColumnType("int");

                    b.Property<string>("SerieName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Broadcasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelId = 1,
                            SerieId = 1,
                            SerieName = "Serie 1"
                        },
                        new
                        {
                            Id = 2,
                            ChannelId = 2,
                            SerieId = 2,
                            SerieName = "Serie 2"
                        });
                });

            modelBuilder.Entity("Howest.models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsChildFriendly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsChildFriendly = false,
                            Name = "VRT"
                        },
                        new
                        {
                            Id = 2,
                            IsChildFriendly = true,
                            Name = "Ketnet"
                        });
                });

            modelBuilder.Entity("Howest.models.Broadcast", b =>
                {
                    b.HasOne("Howest.models.Channel", "Channel")
                        .WithMany("Broadcasts")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Howest.models.Channel", b =>
                {
                    b.Navigation("Broadcasts");
                });
#pragma warning restore 612, 618
        }
    }
}
