apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath # Because we use the hostPath Persistent Volume
