# nodeport-service.yml
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000 # This is the internal port that is being opened inside the Cluster
      targetPort: 3000 # This is the port that is being exposed by the Container
      nodePort: 30000 # This port should be free on the nodes you are using. In the case we are using a multi-node cluster with 3 laptops, each laptop needs to have this port free.
